version: '2'
services:
    dbnode1:
        image: postgres-gis
        hostname: dbnode1
        ports:
            - "5432:5432"
        volumes:
            - data1:/var/lib/postgresql/9.5/main
volumes:
  data1:
