version: '2'
services:
    pg:
        build: ./postgres-gis
        image: postgres-gis
        hostname: pg
        ports:
            - "5432:5432"
        volumes:
            - data-pg:/var/lib/postgresql/9.5/main/
    fill-osm-db:
        build: ./fill-osm-db
        image: fill-osm-db
        command: --checkdb
        environment:
          - PGHOST=pg
          - PGPORT=5432
          - PGUSER=osm
          - PGUSERPW=osm
          - PGADMIN=postgres
          - PGADMINPW=postgres
          - OSM_REGIONS=thueringen
        depends_on:
          - pg
    osm-renderd:
        build: ./osm-renderd
        image: osm-renderd
        volumes:
          - data-tiles:/var/lib/mod_tile/
          - data-renderd-conf:/etc/renderd/
          - /var/run/renderd:/var/run/renderd
        environment:
          - PGHOST=pg
          - PGPORT=5432
          - PGUSER=osm
          - PGUSERPW=osm
          - PGADMIN=postgres
          - PGADMINPW=postgres
        depends_on:
          - fill-osm-db
    apache-www:
        image: osm-renderd
        command: /usr/sbin/apachectl -e info -DFOREGROUND
        volumes:
          - data-tiles:/var/lib/mod_tile/
          - data-renderd-conf:/etc/renderd/
          - /var/run/renderd:/var/run/renderd
        ports:
            - "80:80"
        depends_on:
          - osm-renderd
volumes:
  data-pg:
  data-renderd-conf:
  data-tiles:
